server:
  port: 8082

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/api/user
  data:
      mongodb:
          host: localhost
          port: 27017
          database: microserv_inventory

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

  client:
    registryFetchIntervalSeconds: 5

logging:
  level:
     org.springframework.web: DEBUG

multipart.maxFileSize: 128000KB
multipart.maxRequestSize: 128000KB

---
# For deployment in Docker containers
spring:
  profiles: docker
  oauth2:
    resource:
      userInfoUri: https://auth:9999/uaa/user

server:
  port: 8080

app:
  rabbitmq:
    host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
